name: CI Privileged
permissions:
  contents: read
'on': pull_request_target
jobs:
  is-safe-to-test:
    runs-on: ubuntu-latest
    outputs:
      is_safe: ${{ steps.check.outputs.result }}
    steps:
    - name: Require collaborator or safe-to-test label
      id: check
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: "const pr = context.payload.pull_request;\nconst author = pr.user.login;\n\
          const labels = pr.labels.map(l => l.name);\nconst hasSafeLabel = labels.includes(\"\
          safe-to-test\");\n\nif (hasSafeLabel) return true;\n\nlet isCollaborator\
          \ = false;\ntry {\n  await github.rest.repos.checkCollaborator({\n    owner:\
          \ context.repo.owner,\n    repo: context.repo.repo,\n    username: author\n\
          \  });\n  isCollaborator = true;\n} catch (err) {\n  if (err.status !==\
          \ 404) throw err;\n}\n\nreturn isCollaborator;\n"
  fail-if-unsafe:
    runs-on: ubuntu-latest
    needs: is-safe-to-test
    if: ${{ needs.is-safe-to-test.outputs.is_safe == 'false' }}
    steps:
    - name: Fail if not marked as safe to test
      run: 'echo "Integration tests will not run on a PR unless it has the safe-to-test
        label applied"

        exit 1

        '
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: is-safe-to-test
    if: ${{ needs.is-safe-to-test.outputs.is_safe == 'true' }}
    container:
      image: python:3.11
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.workflow_run.head_repository.full_name }}
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Install dependencies
      run: make dev-env
    - name: Run integration tests
      env:
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        V3IO_FRAMESD: ${{ secrets.V3IO_FRAMESD }}
      run: make integration
